version: '3.9'

services:
  jeroka_db:
    image: postgres:15-alpine
    container_name: jeroka_db
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jeroka
      POSTGRES_DB: jeroka_db
    ports:
      - "5432:5432"
    networks:
      - backend

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://jeroka_db:5432/jeroka_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: jeroka
      JWT_SECRET: o7XhS3kRpD9qFvN1bZcY8wA5mE2jL6tG0iU4xW7zQ8eP3yV1oB2nH6gJ9dK5sT
    depends_on:
      - jeroka_db
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge