urls:
  - url: http://auth-service:8081/v3/api-docs
    name: auth-service
  - url: http://album-service:8083/v3/api-docs
    name: album-service
  - url: http://subscription-service:8084/v3/api-docs
    name: subscription-service
  - url: http://payment-service:8085/v3/api-docs
    name: payment-service
  - url: http://api-gateway:8082/v3/api-docs
    name: api-gateway