server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

springfox:
  documentation:
    swagger:
      v2:
        host: localhost:8084

management:
  endpoints:
    web:
      exposure:
        include: '*'